apply/urls.py
from django.urls import path
from .views import apply

app_name = 'apply'

urlpatterns = [
    path('apply-institution/',apply,name="apply-institution"),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from .views import index,sign_up,sign_in

app_name = 'user'

urlpatterns = [
    path('',index,name='index'),
    path('signup/',sign_up,name='create-user'),
    path('signin/',sign_in,name='login')
]

apply/models.py
from django.db import models

# Create your models here.
class Institution_Type(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

class Apply_Institution(models.Model):
    name = models.CharField(max_length=128)
    address = models.TextField()
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=64)
    country = models.CharField(max_length=64)
    postal_code = models.CharField(max_length=64)
    email = models.EmailField()
    phone = models.CharField(max_length=14)
    date_of_est = models.DateField()
    type = models.ForeignKey(Institution_Type,on_delete=models.SET_NULL,null=True)
    principal = models.CharField(max_length=128)
    no_students = models.IntegerField(max_length=6)
    no_teachers = models.IntegerField(max_length=4)


    def __str__(self):
        return self.name

institution/models.py
from django.db import models
from user.models import User
from tenant_schemas.models import TenantMixin

# Create your models here

class Institution(TenantMixin):
    name = models.CharField(max_length=100)
    paid_until =  models.DateField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created_on = models.DateField(auto_now_add=True)

    auto_create_schema = True

    def __str__(self):
        return self.name

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

apply/forms.py
from django import forms
from .models import Apply_Institution

class ApplyInstitutionForm(forms.ModelForm):
    class Meta:
        model = Apply_Institution
        fields = ['name','address ','city ','state','country','postal_code', 'email','phone', 'date_of_est','type','principal',  'no_students', 'no_teachers',]

apply/views.py
from django.shortcuts import render

# Create your views here.

def apply(request):
    return render(request, 'main/apply.html')

institution/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.db import connection
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout


#custom imports
from .models import User

# Create your views here.

def index(request):
    return render(request, 'index.html')


def sign_up(request):
    if request.method == "POST":
        username = request.POST.get("username")
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        

        if username:
            user = User.objects.filter(username = username)
            if user:
                context = {
                    'fullname' : full_name,
                    'username' : username,
                    'email' : email,
                    'error_username' : "Username taken",
                }
                return render(request, 'main/create_user.html', context)
        
        if email:
            user = User.objects.filter(email= email)
            if user:
                context = {
                    'fullname' : full_name,
                    'username' : username,
                    'email' : email,
                    'error_email' : "Email already in use",
                }
                return render(request, 'main/create_user.html', context)
    
        if password1 != password2:
            context = {
                    'fullname' : full_name,
                    'username' : username,
                    'email' : email,
                    'error_password' : "Password not matching",
            }
            return render(request, 'main/create_user.html', context)

        name_parts = full_name.split()
        if len(name_parts) >= 2:
            last_name = name_parts[-1]
            first_name = ' '.join(name_parts[:-1])
        else:
            first_name = ""
            last_name = full_name

        user = User(first_name=first_name,last_name=last_name,username=username,email=email)
        user.set_password(password1)
        user.save()
        messages.success(request, 'Registration Successful. Now login to your account')

        return redirect('user:login')

    elif request.method == "GET":
        return render(request, 'main/create_user.html')
    else:
        return HttpResponse("Request Method not allowed", status = 405)
    


def sign_in(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('apply:apply-institution')
        else:
            return redirect('user:login')

    elif request.method == "GET":
        return render(request, 'main/login.html')
    else:
        return HttpResponse("Request Method not allowed", status = 405)
    

templates/index.html
<h1>Hello</h1>
<a href="{% url 'user:create-user' %}">Register Instituion</a>

templates/main/app.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>
        {% block title %}
            
        {% endblock title %}
            
    </title>

    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/feather/feather.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/icons/flags/flags.css' %}">
    <link rel="stylesheet" href="{% static '/plugins/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/plugins/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    {% block css %}
        
    {% endblock css %}
        
    
</head>

<body>

    <div class="main-wrapper">

        {% include 'main/navbar.html' %}
        
        {% block content %}
            
        {% endblock content %}
            

    </div>

    
    {% block javascript %}
        
    {% endblock javascript %}
        


    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <script src="{% static 'js/feather.min.js' %}"></script>

    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

    <script src="{% static 'js/form-validation.js' %}"></script>

    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/main/apply.html
{% extends 'main/app.html' %}
{% load static %}


{% block title %}
    Sign Up
{% endblock title %}
    

{% block css %}
<link rel="stylesheet" href="{% static 'css/create-user.css' %}">
{% endblock css %}

{% block content %}
<div class="content container-fluid " style="margin-top: 80px;">

    <div class="page-header">
        <div class="row">
            <div class="col">
                <h3 class="page-title">Basic Inputs</h3>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                    <li class="breadcrumb-item active">Basic Inputs</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Institution Information</h5>
                </div>
                <div class="card-body">
                    <form action="#">
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Institution Name</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Institution Name</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Disabled Input</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" disabled="disabled">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Readonly Input</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" value="readonly"
                                    readonly="readonly">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Placeholder</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" placeholder="Placeholder">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">File Input</label>
                            <div class="col-md-10">
                                <input class="form-control" type="file">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Default Select</label>
                            <div class="col-md-10">
                                <select class="form-control form-select">
                                    <option>-- Select --</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                    <option>Option 4</option>
                                    <option>Option 5</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Radio</label>
                            <div class="col-md-10">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="radio"> Option 1
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="radio"> Option 2
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="radio"> Option 3
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Checkbox</label>
                            <div class="col-md-10">
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="checkbox"> Option 1
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="checkbox"> Option 2
                                    </label>
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="checkbox"> Option 3
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Textarea</label>
                            <div class="col-md-10">
                                <textarea rows="5" cols="5" class="form-control"
                                    placeholder="Enter text here"></textarea>
                            </div>
                        </div>
                        <div class="form-group mb-0 row">
                            <label class="col-form-label col-md-2">Input Addons</label>
                            <div class="col-md-10">
                                <div class="input-group">
                                    <span class="input-group-text">$</span>
                                    <input class="form-control" type="text">
                                    <button class="btn btn-primary" type="button">Button</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Input Sizes</h5>
                </div>
                <div class="card-body">
                    <form action="#">
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Large Input</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control form-control-lg"
                                    placeholder=".form-control-lg">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-2">Default Input</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control" placeholder=".form-control">
                            </div>
                        </div>
                        <div class="form-group mb-0 row">
                            <label class="col-form-label col-md-2">Small Input</label>
                            <div class="col-md-10">
                                <input type="text" class="form-control form-control-sm"
                                    placeholder=".form-control-sm">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}



{% block javascript %}
<script>
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>
{% endblock javascript %}

templates/main/create_user.html
{% extends 'main/app.html' %}
{% load static %}


{% block title %}
    Sign Up
{% endblock title %}
    

{% block css %}
<link rel="stylesheet" href="{% static 'css/create-user.css' %}">
{% endblock css %}

{% block content %}
<div class="main-wrapper login-body">
    <div class="login-wrapper">
        <div class="container">
            <div class="loginbox">
                <div class="login-left">
                    <img class="img-fluid" src="{% static 'img/login.png' %}" alt="Logo">
                </div>
                <div class="login-right">
                    <div class="login-right-wrap">
                        <h1>Sign Up</h1>
                        <p class="account-subtitle">Enter details to create your account</p>

                        <form class="needs-validation" method="POST" action="{% url 'user:create-user' %}" novalidate>
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Full Name <span class="login-danger">*</span></label>
                                <input name="full_name" class="form-control" value="{{fullname}}" type="text" required>
                                <div class="invalid-feedback">
                                    Enter your full name.
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Username <span class="login-danger">*</span></label>
                                <input name="username" value="{{username}}" class="form-control" type="text" required>
                                <span class="profile-views"><i class="fas fa-user-circle"></i></span>
                                <div class="invalid-feedback">
                                    Enter a username.
                                </div>
                                <div class="create-user-form-validate">
                                    {% if error_username %}
                                    {{error_username}}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Email <span class="login-danger">*</span></label>
                                <input name="email" value="{{email}}" class="form-control" type="email" required>
                                <span class="profile-views"><i class="fas fa-envelope"></i></span>
                                <div class="invalid-feedback">
                                    Please enter a valid email.
                                </div>
                                <div class="create-user-form-validate">
                                    {% if error_email %}
                                    {{error_email}}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Password <span class="login-danger">*</span></label>
                                <input name="password1" class="form-control pass-input" type="password" required>
                                <span class="profile-views feather-eye toggle-password"></span>
                                <div class="invalid-feedback">
                                    Please enter password.
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Confirm password <span class="login-danger">*</span></label>
                                <input name="password2" class="form-control pass-confirm" type="password" required>
                                <span class="profile-views feather-eye reg-toggle-password"></span>
                                <div class="invalid-feedback">
                                    Please enter password.
                                </div>
                                <div class="create-user-form-validate">
                                    {% if error_password %}
                                    {{error_password}}
                                    {% endif %}
                                </div>
                            </div>
                            <div class=" dont-have">Already Registered? <a href="{% url 'user:login' %}">Login</a></div>
                            <div class="form-group mb-0">
                                <button class="btn btn-primary btn-block" type="submit">Register</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block javascript %}
<script>
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>
{% endblock javascript %}
    

templates/main/login.html
{% extends 'main/app.html' %}
{% load static %}


{% block title %}
Sign Up
{% endblock title %}


{% block css %}
<link rel="stylesheet" href="{% static 'css/create-user.css' %}">
<link rel="stylesheet" href="{% static 'css/login-user.css' %}">
{% endblock css %}

{% block content %}
<div class="main-wrapper login-body">
    <div class="login-wrapper">
        <div class="container">
            <div class="loginbox">
                <div class="login-left">
                    <img class="img-fluid" src="{% static 'img/login.png' %}" alt="Logo">
                </div>
                <div class="login-right">
                    <div class="login-right-wrap">
                        <h1>Welcome to Preskool</h1>
                        <p class="account-subtitle">Need an account? <a href="{% url 'user:create-user' %}">Sign Up</a></p>
                        <h2>Sign in</h2>

                        <form class="needs-validation" method="POST" action="{% url 'user:login' %}" novalidate>
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Username <span class="login-danger">*</span></label>
                                <input name="username" value="{{username}}" class="form-control" type="text" required>
                                <span class="profile-views"><i class="fas fa-user-circle"></i></span>
                                <div class="invalid-feedback">
                                    Enter a username.
                                </div>
                                <div class="create-user-form-validate">
                                    {% if error_username %}
                                    {{error_username}}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Password <span class="login-danger">*</span></label>
                                <input name="password" class="form-control pass-confirm" type="password" required>
                                <span class="profile-views feather-eye reg-toggle-password"></span>
                                <div class="invalid-feedback">
                                    Please enter password.
                                </div>
                                <div class="create-user-form-validate">
                                    {% if error_password %}
                                    {{error_password}}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="forgotpass">
                                <div class="remember-me">
                                    <label class="custom_check mr-2 mb-0 d-inline-flex remember-me"> Remember me
                                        <input type="checkbox" name="radio">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <a href="forgot-password.html">Forgot Password?</a>
                            </div>

                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    <li
                                    {% if message.tags == "success" %} 
                                        class="messages-success"
                                    {% else %} 
                                        class="messages-error" 
                                    {% endif %}>
                                        {{ message }}
                                    </li>
                                {% endfor %}
                            </ul>
                            {% endif %}

                            <div class="form-group">
                                <button class="btn btn-primary btn-block" type="submit">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block javascript %}
<script>
    (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
                form.addEventListener('submit', function (event) {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false)
            })
    })()
</script>
{% endblock javascript %}

templates/main/navbar.html
{% load static %}
<div class="header">

    <div class="header-left">
        <a href="index.html" class="logo">
            <img src="{% static 'img/logo.png' %}" alt="Logo">
        </a>
        <a href="index.html" class="logo logo-small">
            <img src="{% static 'img/logo-small.png' %}" alt="Logo" width="30" height="30">
        </a>
    </div>


    <ul class="nav user-menu">
        <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Register Institution</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
        </li>

    </ul>

</div>